version: '3.8'
services:
  chat:
    image: gradle:6.6.0-jdk14
    command: sh -c 'gradle --stacktrace -t installDist & gradle run'
    # The directory must be named "omni-chat" because ktor's autoreload watches a directory by that name.
    working_dir: /home/gradle/omni-chat
    ports: [5005:5005] # The debugger attaches to port 5005.
    environment:
      ALLOWED_DOMAINS: example.com,gmail.com
    volumes:
      - type: bind
        source: .
        target: /home/gradle/omni-chat
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
      - type: volume
        source: gradle-cache
        target: /home/gradle/.gradle
volumes:
  gradle-cache: