version: '3.8'
services:
  auth:
    ports: [8080:8080]
  chat:
    image: gradle:6.5.1-jdk14
    command: sh -c 'gradle --no-daemon --stacktrace -t installDist & gradle --no-daemon run'
    # The directory must be named "omni-chat" because ktor's autoreload watches a directory by that name. The directory
    # must be nested (i.e., "/omni-chat" will not work).
    working_dir: /home/gradle/omni-chat
    ports: [80:80]
    volumes:
      - type: bind
        source: .
        target: /home/gradle/omni-chat
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
      - type: volume
        source: gradle-cache
        target: /home/gradle/.gradle
volumes:
  gradle-cache: