version: '3.7'
services:
  auth:
    image: jboss/keycloak:9.0.2
    networks: [auth, auth-db]
    ports: [8080:8080]
    volumes:
      - type: bind
        source: ./docker/dockerize
        target: /docker/dockerize
    environment:
      DB_ADDR: auth-db
      DB_DATABASE: postgres
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      DB_USER: postgres
      DB_VENDOR: postgres
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_USER: admin
  auth-db:
    image: postgres
    networks: [auth-db]
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
  chat:
    entrypoint: docker/dockerize -wait http://auth:8080 -timeout 180s
    networks: [auth, chat-db]
    restart: always
    environment:
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_URL: http://auth:8080/auth
      KEYCLOAK_USER: admin
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
      POSTGRES_URL: chat-db:5432
      POSTGRES_USER: postgres
  chat-db:
    image: postgres:12
    networks: [chat-db]
    environment:
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
networks:
  auth:
  auth-db:
  chat-db: