version: '3.8'
services:
  chat:
    build:
      dockerfile: docker/dev.Dockerfile
      context: .
    command: sh -c 'flyway migrate && gradle --stacktrace -t installDist & gradle run'
    # The directory must be named "omni-chat" because ktor's autoreload watches a directory by that name.
    working_dir: /home/gradle/omni-chat
    ports: [ 5005:5005 ] # The debugger attaches to port 5005.
    environment:
      ALLOWED_EMAIL_DOMAINS: example.com,icloud.com,gmail.com
      FLYWAY_LOCATIONS: filesystem:src/main/resources/db/migration
    volumes:
      - type: bind
        source: .
        target: /home/gradle/omni-chat
        consistency: cached # Prevents Docker for Mac bind mounts from being unusably slow.
      - type: volume
        source: gradle-cache
        target: /home/gradle/.gradle
volumes:
  gradle-cache:
