version: '3.7'
services:
  auth:
    ports: [8080:8080]
  chat:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports: [80:80]
    command: java
      -server
      -XX:+UnlockExperimentalVMOptions
      -XX:+UseCGroupMemoryLimitForHeap
      -XX:InitialRAMFraction=2
      -XX:MinRAMFraction=2
      -XX:MaxRAMFraction=2
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=100
      -XX:+UseStringDeduplication
      -jar
      omni-chat-all.jar