version: '3.8'
services:
  chat:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: sh -c 'flyway migrate && java -server -jar omni-chat-backend.jar'
    environment:
      ALLOWED_EMAIL_DOMAINS: ${ALLOWED_EMAIL_DOMAINS}
