# Name `operationId`s using the format <<HTTP_METHOD><PATH>> (e.g., <patchProfileImage> for HTTP PATCH /profile-image).
openapi: 3.0.3
info:
  version: 0.23.0
  title: Omni Chat
  description: |
    Functionality supplementary to the GraphQL API such as uploading and downloading images.

    In this documentation, a _thumbnail_ refers to an image no bigger than 100px by 100px. These images are at most a
    few KiB. If the original image itself is within 100px by 100px, then the thumbnail will happen to be a copy of the
    same image. When displaying a small scaled image (e.g., a profile image) you should only render the thumbnail, and
    not load the original, since the difference in quality is negligible. When showing a image in a container larger
    than 100px (e.g., a image message, an enlarged profile image), you should load the original. You can also initially
    load the thumbnail followed by the original for a medium-scaled image (e.g., the way searching images on Google
    works).
  contact:
    name: Neel Kamath
    url: https://github.com/neelkamath/omni-chat-backend
    email: neelkamathonline@gmail.com
  license:
    name: MIT
    url: https://github.com/neelkamath/omni-chat-backend/blob/master/LICENSE
servers:
  - url: http://localhost
    description: This is the URL if you're running it locally. Otherwise, it's the URL you or someone else is running it
      on.
tags:
  - name: profileImage
  - name: groupChatImage
  - name: imageMessage
  - name: audioMessage
  - name: videoMessage
  - name: docMessage
  - name: status
paths:
  /image-message:
    description: Create and read image chat messages.
    get:
      tags: [ imageMessage ]
      description: Reads the image from a message. To get the caption, use the GraphQL API. You needn't pass an access
        token if the chat is public.
      operationId: getImageMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/MessageId'
        - $ref: '#/components/parameters/ImageType'
      responses:
        '200':
          $ref: '#/components/responses/Image'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags: [ imageMessage ]
      description: Creates a image message.
      operationId: postImageMessage
      security:
        - bearerAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/CaptionedImage'
      responses:
        '204':
          description: Message created.
        '400':
          $ref: '#/components/responses/InvalidImageMessage'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /audio-message:
    description: Create and read audio chat messages.
    get:
      tags: [ audioMessage ]
      description: Reads an audio message. You needn't pass an access token if the chat is public.
      operationId: getAudioMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      responses:
        '200':
          $ref: '#/components/responses/Audio'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags: [ audioMessage ]
      description: Creates an audio message.
      operationId: postAudioMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/ChatId'
        - $ref: '#/components/parameters/ContextMessageId'
      requestBody:
        $ref: '#/components/requestBodies/AudioMessage'
      responses:
        '204':
          description: Message created.
        '400':
          $ref: '#/components/responses/InvalidMediaMessage'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /video-message:
    description: Create and read video chat messages.
    get:
      tags: [ videoMessage ]
      description: Reads a video message. You needn't pass an access token if the chat is public.
      operationId: getVideoMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      responses:
        '200':
          $ref: '#/components/responses/Video'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags: [ videoMessage ]
      description: Creates a video message.
      operationId: postVideoMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/ChatId'
        - $ref: '#/components/parameters/ContextMessageId'
      requestBody:
        $ref: '#/components/requestBodies/VideoMessage'
      responses:
        '204':
          description: Message created.
        '400':
          $ref: '#/components/responses/InvalidMediaMessage'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /doc-message:
    description: Create and read document chat messages. Doc messages are file messages of any type. Prefer image
      audio, and video messages when possible.
    get:
      tags: [ docMessage ]
      description: Reads a doc message. You needn't pass an access token if the chat is public.
      operationId: getDocMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      responses:
        '200':
          $ref: '#/components/responses/Doc'
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      tags: [ docMessage ]
      description: Creates a doc message.
      operationId: postDocMessage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/ChatId'
        - $ref: '#/components/parameters/ContextMessageId'
      requestBody:
        $ref: '#/components/requestBodies/DocMessage'
      responses:
        '204':
          description: Message created.
        '400':
          $ref: '#/components/responses/InvalidMediaMessage'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /profile-image:
    description: A user's profile image which doesn't exceed 3 MiB.
    get:
      tags: [ profileImage ]
      description: Get the user's profile image.
      operationId: getProfileImage
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/ImageType'
      responses:
        '200':
          $ref: '#/components/responses/Image'
        '204':
          description: The user doesn't have a profile image.
        '400':
          description: The user doesn't exist.
    patch:
      tags: [ profileImage ]
      description: Update the user's profile image.
      operationId: patchProfileImage
      security:
        - bearerAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/Image'
      responses:
        '204':
          description: Image updated.
        '400':
          $ref: '#/components/responses/InvalidImage'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /group-chat-image:
    get:
      tags: [ groupChatImage ]
      description: Retrieves the group chat's image.
      operationId: getGroupChatImage
      parameters:
        - $ref: '#/components/parameters/ChatId'
        - $ref: '#/components/parameters/ImageType'
      responses:
        '200':
          $ref: '#/components/responses/Image'
        '204':
          description: The chat doesn't have a image.
        '400':
          description: Invalid chat ID.
    patch:
      tags: [ groupChatImage ]
      description: Update the group chat's image. The user must be an admin of the chat.
      operationId: patchGroupChatImage
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/ChatId'
      requestBody:
        $ref: '#/components/requestBodies/Image'
      responses:
        '204':
          description: Image updated.
        '400':
          description: The file had an invalid type or size.
        '401':
          $ref: '#/components/responses/Unauthorized'
  /health-check:
    get:
      tags: [ status ]
      description: Check if all systems are operational. For example, a backend developer building atop Omni Chat can
        program the server to automatically restart when it becomes "unhealthy".
      operationId: getHealthCheck
      responses:
        '204':
          description: Healthy.
components:
  schemas:
    InvalidMediaMessage:
      type: object
      properties:
        reason:
          description: An `"INVALID_FILE"` indicates that the file's type or size was unacceptable. A `"MUST_BE_ADMIN"`
            indicates that the chat is a broadcast chat, and the user isn't an admin.
          type: string
          enum: [ USER_NOT_IN_CHAT, INVALID_FILE, INVALID_CONTEXT_MESSAGE, MUST_BE_ADMIN ]
    InvalidImageMessage:
      type: object
      properties:
        reason:
          description: An `"INVALID_FILE"` indicates that the file's type or size was unacceptable. A `"MUST_BE_ADMIN"`
            indicates that the chat is a broadcast chat, and the user isn't an admin.
          type: string
          enum: [ USER_NOT_IN_CHAT, INVALID_FILE, INVALID_CONTEXT_MESSAGE, INVALID_CAPTION, MUST_BE_ADMIN ]
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    InvalidMediaMessage:
      description: Couldn't create message.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvalidMediaMessage'
    InvalidImageMessage:
      description: Couldn't create message.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvalidImageMessage'
    Audio:
      description: An MP3/MP4 video not exceeding 3 MiB.
      content:
        audio/mp3, audio/mp4:
          schema:
            type: string
            format: binary
    Video:
      description: An MP4 video not exceeding 3 MiB.
      content:
        video/mp4:
          schema:
            type: string
            format: binary
    Doc:
      description: A document not exceeding 3 MiB.
      content:
        '*/*':
          schema:
            type: string
            format: binary
    Image:
      description: A PNG or JPEG image not exceeding 3 MiB.
      content:
        image/png, image/jpeg:
          schema:
            type: string
            format: binary
    Thumbnail:
      description: A PNG or JPEG image.
      content:
        image/png, image/jpeg:
          schema:
            type: string
            format: binary
    InvalidImage:
      description: Image wasn't a PNG or JPEG not exceeding 3 MiB.
    Unauthorized:
      description: Invalid or missing auth token.
  requestBodies:
    AudioMessage:
      content:
        multipart/form-data:
          schema:
            type: object
            required: [ audio ]
            properties:
              audio:
                description: An MP3/MP4 audio not exceeding 3 MiB.
                type: string
                format: binary
          encoding:
            image:
              contentType: audio/mp3, audio/mp4
    VideoMessage:
      content:
        multipart/form-data:
          schema:
            type: object
            required: [ video ]
            properties:
              video:
                description: An MP4 video not exceeding 3 MiB.
                type: string
                format: binary
          encoding:
            image:
              contentType: video/mp4
    DocMessage:
      content:
        multipart/form-data:
          schema:
            type: object
            required: [ doc ]
            properties:
              doc:
                description: A document not exceeding 3 MiB.
                type: string
                format: binary
    CaptionedImage:
      content:
        multipart/form-data:
          schema:
            type: object
            required: [ image, chat-id ]
            properties:
              image:
                description: A PNG or JPEG image not exceeding 3 MiB.
                type: string
                format: binary
              chat-id:
                type: integer
                description: Chat to message in.
              context-message-id:
                description: The user might want to give their message a context, such as when replying to a message
                  sent several messages ago. In this case, this is the ID of the message being replied to.
                type: integer
              caption:
                type: string
                description: The image's caption. Must be a valid `scalar MessageText` (refer to the GraphQL schema).
          encoding:
            image:
              contentType: image/png, image/jpeg
    Image:
      content:
        multipart/form-data:
          schema:
            type: object
            required: [ image ]
            properties:
              image:
                description: A PNG or JPEG image not exceeding 3 MiB.
                type: string
                format: binary
          encoding:
            image:
              contentType: image/png, image/jpeg
  parameters:
    UserId:
      name: user-id
      in: query
      description: The ID of the user the image is to be retrieved from.
      required: true
      schema:
        type: integer
    ImageType:
      name: image-type
      in: query
      description: Whether to retrieve the original or the thumbnail.
      required: true
      schema:
        type: string
        enum: [ ORIGINAL, THUMBNAIL ]
    ChatId:
      name: chat-id
      in: query
      description: Chat ID.
      required: true
      schema:
        type: integer
    MessageId:
      name: message-id
      in: query
      description: Message ID.
      required: true
      schema:
        type: integer
    ContextMessageId:
      name: context-message-id
      in: query
      description: The user might want to give their message a context, such as when replying to a message sent several
        messages ago. In this case, this is the ID of the message being replied to.
      schema:
        type: integer
