on: push
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp docs/.example.env .env
      - name: test
        run: |
          docker-compose \
            -f docker/docker-compose.yml \
            -f docker/docker-compose.test.yml \
            --project-directory . \
            up --abort-on-container-exit --exit-code-from chat
      - if: always()
        uses: actions/upload-artifact@v1
        with:
          name: server-test-results
          path: build/reports/tests/test/
  github-release:
    if: github.ref == 'refs/heads/master'
    needs: test-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew --no-daemon githubRelease -PGITHUB_PAT=${{ secrets.GITHUB_PAT }}