on: push
jobs:
  test-server:
    runs-on: ubuntu-latest
    container: openjdk:8
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew test
      - uses: actions/upload-artifact@v1
        with:
          name: server-test-results
          path: build/reports/tests/test/
  test-spec:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - uses: actions/checkout@v2
      - run: npx @stoplight/spectral lint docs/openapi.yaml
  build-docs:
    if: github.ref == 'master'
    needs: [test-server, test-spec]
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - uses: actions/checkout@v2
      - run: npx redoc-cli bundle docs/openapi.yaml --title 'Omni Chat'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: redoc-static.html
  github-release:
    needs: build-docs
    runs-on: ubuntu-latest
    container: openjdk:8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: docs
      - run: ./gradlew --no-daemon githubRelease -PGITHUB_PAT=$GITHUB_PAT
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
  host-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: docs
          path: public/index.html
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: public
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}