on: push
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew --no-daemon test
      - if: always()
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - if: always()
        uses: actions/upload-artifact@v1
        with:
          name: server-test-results
          path: build/reports/tests/test/
  test-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npx @stoplight/spectral lint docs/openapi.yaml
  build-docs:
    if: github.ref == 'master'
    needs: [test-server, test-spec]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npx redoc-cli bundle docs/openapi.yaml --title 'Omni Chat'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: redoc-static.html
  github-release:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: docs
      - if: always()
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew --no-daemon githubRelease -PGITHUB_PAT=$GITHUB_PAT
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
  host-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: docs
          path: public/index.html
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: public
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}